// eslint-disable-next-line import/no-anonymous-default-export
export const data = [
  {
    id: 0,
    name: "Апдейт угоди",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "09.10.2020",
    time: "17:00",
  },
  {
    id: 1,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "14:00",
  },
  {
    id: 2,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "14:00",
  },
  {
    id: 3,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "19:00",
  },
  {
    id: 4,
    name: "Апдейт угоди",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020  14:00",
    time: "17:00",
  },
  {
    id: 5,
    name: "Список вільних столиків",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "18:00",
  },
  {
    id: 6,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "14:00",
  },
  {
    id: 7,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "09:00",
  },
  {
    id: 8,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "17:00",
  },
  {
    id: 9,
    name: "Список вільних столиків",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "14:00",
  },
  {
    id: 10,
    name: "Апдейт угоди",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "12.10.2020",
    time: "10:00",
  },
  {
    id: 11,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "17:00",
  },
  {
    id: 12,
    name: "Апдейт угоди",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "19:00",
  },
  {
    id: 13,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "14.10.2020",
    time: "20:00",
  },
  {
    id: 14,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "15:30",
  },
  {
    id: 15,
    name: "Список вільних столиків",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "17:40",
  },
  {
    id: 16,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020  14:00",
    time: "17:40",
  },
  {
    id: 17,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "17:00",
  },
  {
    id: 18,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "17:00",
  },
  {
    id: 19,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "19:40",
  },
  {
    id: 20,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "17:40",
  },
  {
    id: 21,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "11.10.2020",
    time: "17:40",
  },
  {
    id: 22,
    name: "Список вільних столиків",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "12:40",
  },
  {
    id: 23,
    name: "Список вільних столиків",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "10.10.2020",
    time: "14:00",
  },
  {
    id: 24,
    name: "Статус посилки",
    url: "https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/",
    author: "Алла Гриценко",
    createAt: "16.10.2020",
    time: "17:50",
  },
];
